[package]
name = "cpu3"
version = "0.1.0"
authors = ["mickeey2525 <m.tachibana25@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
